name = "prompt-forge"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

main = "src/worker/index.ts"

[assets]
directory = "./dist/"

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketServer"]

[[d1_databases]]
binding = "DB"
database_name = "promptforge-store"
database_id = "636160e6-3995-4385-81a7-1cf2e79908ed"

[observability.logs]
enabled = false

