name = "prompt-forge"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

main = "src/worker/index.ts"

[assets]
directory = "./dist/"

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketServer"]

[[d1_databases]]
binding = "DB"
database_name = "promptforge-store"
database_id = "1c9b5dae-f1fa-49d8-83fa-7bd5b39c4121"
