name = "prompt-forge"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

main = "src/worker/index.ts"

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"
run_worker_first = ["/ws/*"]

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketServer"]

[[d1_databases]]
binding = "DB"
database_name = "promptforge-store"
database_id = "6961b5fe-6734-4129-a5eb-83412941264c"

[observability.logs]
enabled = false

